#!/usr/bin/env node
// Build-time image pipeline:
//   - Finds every PNG/JPEG under public/ (except favicon)
//   - Generates AVIF + WebP variants at multiple widths
//   - Generates a tiny WebP blur placeholder
//   - Writes a TS manifest to src/generated/imageManifest.ts
//
// AVIF encoding uses `avifenc` (libavif) for best quality.
// Resizing and WebP encoding use `sharp`.

import { spawn } from 'node:child_process';
import { promises as fs } from 'node:fs';
import path from 'node:path';
import sharp from 'sharp';

const ROOT = process.cwd();
const PUBLIC_DIR = path.join(ROOT, 'public');
const OUT_DIR = path.join(PUBLIC_DIR, '_img');
const MANIFEST_PATH = path.join(ROOT, 'src', 'generated', 'imageManifest.ts');

const TARGET_WIDTHS = [384, 640, 750, 828, 1080, 1200, 1920, 2560];
const AVIF_QUALITY = 65;
const AVIF_SPEED = 6;
const WEBP_QUALITY = 80;

const SKIP = new Set([path.join(PUBLIC_DIR, 'logo', 'favicon.png')]);

async function walk(dir) {
  const out = [];
  for (const entry of await fs.readdir(dir, { withFileTypes: true })) {
    const full = path.join(dir, entry.name);
    if (entry.isDirectory()) {
      if (entry.name === '_img') continue;
      out.push(...(await walk(full)));
    } else if (/\.(png|jpe?g)$/i.test(entry.name)) {
      out.push(full);
    }
  }
  return out;
}

async function shouldSkip(src, dst) {
  try {
    const [s, d] = await Promise.all([fs.stat(src), fs.stat(dst)]);
    return d.mtimeMs >= s.mtimeMs;
  } catch {
    return false;
  }
}

function encodeAvif(pngBuffer, outPath) {
  return new Promise((resolve, reject) => {
    const proc = spawn('avifenc', [
      '-q', String(AVIF_QUALITY),
      '-s', String(AVIF_SPEED),
      '--stdin', '--input-format', 'png',
      outPath,
    ]);
    let stderr = '';
    proc.stderr.on('data', (c) => { stderr += c.toString(); });
    proc.on('error', reject);
    proc.on('close', (code) => {
      if (code === 0) resolve();
      else reject(new Error(`avifenc exited ${code}: ${stderr}`));
    });
    proc.stdin.end(pngBuffer);
  });
}

async function ensureDir(p) {
  await fs.mkdir(path.dirname(p), { recursive: true });
}

async function processImage(srcAbs) {
  const relFromPublic = path.relative(PUBLIC_DIR, srcAbs);
  const urlPath = '/' + relFromPublic.split(path.sep).join('/');
  const noExt = urlPath.replace(/\.(png|jpe?g)$/i, '');

  const meta = await sharp(srcAbs).metadata();
  const intrinsicW = meta.width ?? 0;
  const intrinsicH = meta.height ?? 0;
  if (!intrinsicW || !intrinsicH) {
    throw new Error(`Could not read dimensions of ${srcAbs}`);
  }

  const widths = Array.from(new Set(
    TARGET_WIDTHS.filter((w) => w < intrinsicW).concat([intrinsicW])
  )).sort((a, b) => a - b);

  for (const w of widths) {
    const baseOut = path.join(OUT_DIR, noExt.replace(/^\//, '') + `-${w}`);
    const avifOut = baseOut + '.avif';
    const webpOut = baseOut + '.webp';
    await ensureDir(avifOut);

    const needsAvif = !(await shouldSkip(srcAbs, avifOut));
    const needsWebp = !(await shouldSkip(srcAbs, webpOut));

    if (needsAvif || needsWebp) {
      const resizer = sharp(srcAbs).resize({ width: w, withoutEnlargement: true });

      if (needsWebp) {
        await resizer.clone().webp({ quality: WEBP_QUALITY }).toFile(webpOut);
      }
      if (needsAvif) {
        const pngBuf = await resizer.clone().png({ compressionLevel: 0 }).toBuffer();
        await encodeAvif(pngBuf, avifOut);
      }
    }
  }

  const blurBuffer = await sharp(srcAbs).resize(16).webp({ quality: 30 }).toBuffer();
  const blurDataURL = `data:image/webp;base64,${blurBuffer.toString('base64')}`;

  return {
    key: urlPath,
    entry: { width: intrinsicW, height: intrinsicH, widths, blurDataURL },
  };
}

async function writeManifest(entries) {
  await fs.mkdir(path.dirname(MANIFEST_PATH), { recursive: true });
  const sorted = [...entries].sort((a, b) => a.key.localeCompare(b.key));
  const body = sorted.map(({ key, entry }) => {
    return `  ${JSON.stringify(key)}: ${JSON.stringify(entry)},`;
  }).join('\n');
  const content = `// AUTO-GENERATED by scripts/build-images.mjs — do not edit by hand.
export type ImageManifestEntry = {
  width: number;
  height: number;
  widths: number[];
  blurDataURL: string;
};

export const imageManifest: Record<string, ImageManifestEntry> = {
${body}
};
`;
  await fs.writeFile(MANIFEST_PATH, content, 'utf8');
}

async function main() {
  console.log('Scanning public/ for PNG/JPEG sources...');
  const all = await walk(PUBLIC_DIR);
  const sources = all.filter((p) => !SKIP.has(p));
  console.log(`Found ${sources.length} source image(s).`);

  const entries = [];
  for (let i = 0; i < sources.length; i++) {
    const src = sources[i];
    const rel = path.relative(ROOT, src);
    process.stdout.write(`[${i + 1}/${sources.length}] ${rel} ... `);
    const result = await processImage(src);
    entries.push(result);
    console.log(`${result.entry.widths.length} width(s)`);
  }

  await writeManifest(entries);
  console.log(`Wrote manifest: ${path.relative(ROOT, MANIFEST_PATH)}`);
  console.log('Done.');
}

main().catch((err) => {
  console.error(err);
  process.exit(1);
});
